openapi: 3.0.1
info:
  title: Nexpose Resources
  description: Scripts, SQL queries, and other resources for Nexpose
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/nexpose-resources 
  x-cortex-tag: nexpose-resources
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: insightvm
  x-cortex-groups:
   - target:not-deployed
   - strategy:on-prem
   - exposure:external-ship
